title: blog.jfo.click

permalink: /:title/
# gems:
#   - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

defaults:
    -
        scope:
            path: "" # an empty string here means all files in the project
        values:
            layout: "base"
